import ajax from './ajax'
export const req_address = (longitude,latitude)=>ajax(`/position/${latitude},${longitude}`)
export const req_categorys = ()=>ajax('/index_category',{headers:{needcheck:true}})
export const req_shops = ({longitude,latitude})=>ajax('/shops',{params: {latitude,longitude},headers:{needcheck:true}})
export const req_sendcode = (phone)=>ajax.get('/sendcode',{params: {phone}})
export const req_loginpwd = ({name,pwd,captcha})=>ajax.post('/login_pwd',{name,pwd,captcha})
export const req_loginsms = ({phone,code})=>ajax.post('/login_sms',{phone,code})
export const req_autoLogin = ()=>ajax.get('/auto_login')
export const req_goods = ()=>ajax.get('/goods')
export const req_ratings = ()=>ajax.get('/ratings')
export const req_info = ()=>ajax.get('/info')